from datetime import datetime

from sqlalchemy.orm import Session

from backend.models.alert import Alert
from backend.models.incident import Incident, IncidentTimeline
from backend.models.user import User


def generate_incident_for_alert(
    db: Session,
    alert: Alert,
    assigned_analyst: int | None = None
):
    """
    Create an incident for a qualifying alert.

    Returns:
        Incident object if created.
        Existing Incident if already linked.
        None if the alert does not require an incident.
    """
    # Automatically create incidents for critical alerts
    # and high-confidence correlation alerts.
    high_confidence_rules = {
        "FAILED_LOGIN_SPIKE",
    }

    if (
        alert.severity != "CRITICAL"
        and alert.rule_name not in high_confidence_rules
    ):
        return None
    # Prevent duplicate incidents for the same alert.
    existing = (
        db.query(Incident)
        .filter(
            Incident.alert_id == alert.id
        )
        .first()
    )

    if existing:
        return existing

    # Automatically assign an active security analyst
    # when no analyst was explicitly supplied.
    if assigned_analyst is None:

        analyst = (
            db.query(User)
            .filter(
                User.role == "SECURITY_ANALYST",
                User.is_active == True
            )
            .order_by(User.id)
            .first()
        )

        if analyst:
            assigned_analyst = analyst.id

    incident_id = (
        f"INC-{datetime.utcnow().strftime('%Y')}-"
        f"{alert.id:03d}"
    )

    # Protect against an incident ID collision.
    existing_id = (
        db.query(Incident)
        .filter(
            Incident.incident_id == incident_id
        )
        .first()
    )

    if existing_id:
        incident_id = (
            f"INC-{datetime.utcnow().strftime('%Y')}-"
            f"{alert.id:03d}-1"
        )

    incident = Incident(
        incident_id=incident_id,
        alert_id=alert.id,
        asset_id=alert.asset_id,
        title=(
            f"Investigation: {alert.title}"
        ),
        severity=alert.severity,
        detection_time=alert.trigger_time,
        assigned_analyst=assigned_analyst,
        status="OPEN",
        investigation_notes=(
            "Incident automatically created from "
            f"alert {alert.alert_id}."
        ),
        evidence=(
            alert.description
            or "Alert generated by the detection engine."
        ),
        containment_action=None,
        root_cause=None,
        resolution=None,
        preventive_action=(
            "Investigate the alert, determine root cause "
            "and review applicable security controls."
        ),
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    )

    db.add(incident)
    db.flush()

    timeline = IncidentTimeline(
        incident_id=incident.id,
        event_time=datetime.utcnow(),
        action="INCIDENT_CREATED",
        description=(
            f"Incident automatically created from "
            f"alert {alert.alert_id}."
        ),
        performed_by=assigned_analyst,
        created_at=datetime.utcnow(),
    )

    db.add(timeline)

    db.flush()

    return incident
